name: Fetch audit log activity

on:
  schedule:
    - cron: "0 1 * * 1-6"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: oss-tooling/user-inactivity/.github/actions/audit@v1.0.2
        with:
          org: oss-tooling
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}