name: Remove inactive users from the org

on:
  schedule:
    - cron: "15 12 * * 4"
  workflow_dispatch:

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - uses: oss-tooling/user-inactivity/.github/actions/kick@v1
        with:
          org: oss-tooling
          repo: _activity
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}